default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("DEVELOPMENT_DB_NAME") %>
  username: <%= ENV.fetch("DEVELOPMENT_DB_USERNAME") %>
  password: <%= ENV.fetch("DEVELOPMENT_DB_PASSWORD") %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME") %>
  username: <%= ENV.fetch("TEST_DB_USERNAME") %>
  password: <%= ENV.fetch("TEST_DB_PASSWORD") %>

production:
  <<: *default
  database: <%= ENV.fetch("PRODUCTION_DB_NAME") %>
  username: <%= ENV.fetch("PRODUCTION_DB_USERNAME") %>
  password: <%= ENV.fetch("PRODUCTION_DB_PASSWORD") %>

